name: master
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        deno: ["1.5.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Integration
        run: |
          deno cache mod.ts
          deno test --allow-read --allow-run --allow-write --allow-net tests/integration

      - name: Ensure Permissions Work
        run: |
          cd tests/integration/out-of-date-deps
          deno run --allow-read='.' --allow-write='deps.ts' --allow-net='x.nest.land,cdn.deno.land,api.deno.land,raw.githubusercontent.com,github.com,api.github.com' ../../../mod.ts update
  linting:
    strategy:
      matrix:
        deno: ["1.5.1"]
    # Doesn't need to be checked in all OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
        
      - name: Check Code FMT
        run: deno fmt --check
