name: master
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        deno: ["1.3.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Integration
        run: |
          deno cache mod.ts
          deno test --allow-read --allow-run --allow-write --allow-net tests/integration

      - name: Install
        run: |
          deno install --allow-read --allow-run --allow-write --allow-net https://deno.land/x/dmm/mod.ts

  linting:
    strategy:
      matrix:
        deno: ["1.3.1"]
    # Doesn't need to be checked in all OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
        
      - name: Check Code FMT
        run: deno fmt --check
